spring:
  application:
    name: library-management-be

  datasource:
    url: jdbc:postgresql://localhost:5432/library_management
    username: postgres
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create